export function Decks() {
  return [
    {
      name: "test deck",
      id: "test",
      startingBeing: "Pyromancer",
      startingLocation: "Bathurst",
      decklist: {
        "Dense Forest": 40,
      },
    },
    {
      name: "Fire Deck",
      id: "fire",
      startingBeing: "Pyromancer",
      startingLocation: "Bathurst",
      decklist: {
        "Short Sword": 3,
        "Small Shield": 3,
        "Dense Forest": 4,
        "Iron Mine": 4,
        "Pathway": 4,
        "Fireball": 4,
        "Flame Weapon": 2,
        "Firey Grenade": 2,
        "Little Red Potion": 4,
        // "Wizard Tower": 3,
        // 'Commerce': 3,
        // 'Campfire': 3,
        // 'Obsidian Mine': 3,
        // 'Fire Core': 1,
        // 'Hero': 2,
        // 'Fire Rogue': 3,
        // 'Pyromancer': 3,
        // 'Berserker': 2,
        // 'Tree-on-Cliff': 3,
        // 'Farmhouse': 3,
        // 'Dwarven Fortress': 2,
        // 'Shortsword': 3,
        // 'Sledgehammer': 3
      },
    },
    {
      name: "Water Deck",
      id: "water",
      startingBeing: "Water Wizard",
      startingLocation: "Suffragette City",
      decklist: {
        Tank: 4,
        Druid: 2,
        Thief: 3,
        "Short Sword": 3,
        "Small Shield": 3,
        "Dense Forest": 3,
        "Iron Mine": 3,
        "Grumpy's Farm": 3,
        "Great Gate": 1,
        "Firey Grenade": 4,
        "Little Red Potion": 4,
        // 'Commerce': 3,
        // 'Campfire': 3,
        // 'Obsidian Mine': 3,
        // 'Fire Core': 1,
        // 'Hero': 2,
        // 'Fire Rogue': 3,
        // 'Pyromancer': 3,
        // 'Berserker': 2,
        // 'Tree-on-Cliff': 3,
        // 'Farmhouse': 3,
        // 'Dwarven Fortress': 2,
        // 'Shortsword': 3,
        // 'Sledgehammer': 3
      },
    },
    {
      name: "Earth Deck",
      id: "earth",
      startingBeing: "Druid",
      startingLocation: "Suffragette City",
      decklist: {
        Tank: 2,
        Thief: 2,
        "Short Sword": 3,
        "Small Shield": 3,
        "Dense Forest": 3,
        "Grumpy's Farm": 3,
        "Glowy Weapon": 2,
        "Lil' Bear": 2,
        "Firey Grenade": 4,
        "Little Red Potion": 4,
        // 'Commerce': 3,
        // 'Campfire': 3,
        // 'Obsidian Mine': 3,
        // 'Fire Core': 1,
        // 'Hero': 2,
        // 'Fire Rogue': 3,
        // 'Pyromancer': 3,
        // 'Berserker': 2,
        // 'Tree-on-Cliff': 3,
        // 'Farmhouse': 3,
        // 'Dwarven Fortress': 2,
        // 'Shortsword': 3,
        // 'Sledgehammer': 3
      },
    },
  ];
}
